require "bundler/setup"

require "rspec/core/rake_task"
require "rspec/core/version"

desc "Run all specs"
RSpec::Core::RakeTask.new(:spec) do |t|
  t.rspec_opts = %w[--color --format documentation --require ./spec/spec_helper]
end
